name: Reject PRs

on:
  pull_request_target:
    types: [opened, reopened]
    paths:
      - docs/index.html

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Hi. Thanks for your PR. However, `index.html` is a generated file. Please update `index.tt` instead."
